### ISSUE TITLE
Jittery tooltips

### ISSUE THREAD

**Issue by Shians** [JEFworks/ubit2#26]
Very cool software! I noticed that the tooltips are a bit jittery when you move your mouse around, this is especially noticeable when mousing horizontally across a cell on the heatmap of your [front page](http://pklab.med.harvard.edu/jean/ubit2/).

I've run into a similar issue in my software and it was due to [pointer-events](https://developer.mozilla.org/en/docs/Web/CSS/pointer-events) triggering on the tooltip box which appears in front of the elements. Hopefully setting the CSS of the tooltip to ```pointer-events: none``` fixes your problem as it did mine.

**Comment by JEFworks** [comment]
Hey Shian,

Thanks so much for the suggestion! If you'd be interested in editing the CSS and making a pull request, I'd be happy to merge your changes so you can get credit for your contribution. Just let me know. 

Thanks again,
Jean

**Comment by Shians** [comment]
Has been fixed by #27
