### ISSUE TITLE
interactive data tables

### ISSUE THREAD

**Issue by slowkow** [JEFworks/ubit2#9]
Consider using a spreadsheet to present the data with one of these libraries:
- [ ] [handsontable](https://handsontable.com/examples.html?headers&sorting) this is probably this simplest way to go
- [ ] [DataTables](https://www.datatables.net/examples/basic_init/scroll_xy.html) this may also be a good way to go
- [ ] [SlickGrid](https://github.com/mleibman/SlickGrid) another fast library with lots of features
- [ ] [fattable](https://github.com/fulmicoton/fattable) this has the least number of features, but maybe it is more lightweight than the other options

Consider allowing users to copy data from the app into their clipboard with [cliboard.js](https://github.com/zenorocha/clipboard.js).

Consider using a pivot table to let the user explore metadata for each sample:
- [ ] [pivottable](http://nicolas.kruchten.com/pivottable/examples/)

![pivottable_animation](https://cloud.githubusercontent.com/assets/209714/13123714/8c38373e-d58b-11e5-92e0-9f7b52518ade.gif)

**Comment by JEFworks** [comment]
handsontable integrated in 68f72eb
